# Основные настройки
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "full"
startup_mode = "Windowed"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16.0
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }

# Курсор
[cursor]
style = { shape = "Block" }
blink_interval = 0
unfocused_hollow = true

# Мышь
[mouse]
hide_when_typing = false

[colors]
primary = { background = "#2E3440", foreground = "#D8DEE9" }
cursor = { text = "#2E3440", cursor = "#D8DEE9" }
selection = { text = "#D8DEE9", background = "#434C5E" }

